plugins { id 'com.android.application' }
android {
    namespace 'id.jhx.tools'
    compileSdk 34
    defaultConfig {
        applicationId 'id.jhx.tools'
        minSdk 24
        targetSdk 34
        versionCode 7
        versionName '2.7'
    }
    signingConfigs {
        release {
            storeFile file('../jhtools.keystore')
            storePassword 'jhtools123'
            keyAlias 'jhtools'
            keyPassword 'jhtools123'
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
